tests: Fix test_linux_boot_mesh.py test name
The previous name, copy pasted from test_linux_boot.py was
formatted using the mem_system variable which is not
defined for custom mesh test (since it works with CHI
only)

As a consequence testlib was throwing an exception

    exec(open(path).read(), newdict, newdict)
  File "<string>", line 103, in <module>
  File "<string>", line 53, in test_boot_mesh
NameError: name 'mem_system' is not defined
[...]
Ignoring all tests in this file.

Needless to say testlib was therefore silently ignoring
the suite altogether, as can be seen by the log
above.

Change-Id: Idde3977e4553422eb223f4dea872e719ce37feac
Signed-off-by: Giacomo Travaglini <giacomo.travaglini@arm.com>