arch-arm: Fix self-assign warnings in Arm NEON instructions
My compiler gave a warning about self assignment
 error: explicitly assigning value of variable of type 'uint32_t' (aka 'unsigned int') to itself [-Werror,-Wself-assign]

This change removes self assignments in the NEON instructions.
This is a separate commit since it looks like it could change behavior.

Signed-off-by: Jason Lowe-Power <jlowepower@google.com>