dev-arm: fix --generate-dtb for ARM
Was failing with:

NameError: global name 'FdtNode' is not defined

The problem was introduced at: 75831ce5b7880b67c1aa2e0871ce16d5c01cadc7

Change-Id: I7e2ce0e5311e7814229945b9f4e7318a8652dc1f
Reviewed-by: Andreas Sandberg <andreas.sandberg@arm.com>
Reviewed-on: https://gem5-review.googlesource.com/c/15875
Maintainer: Andreas Sandberg <andreas.sandberg@arm.com>