cpu: Remove private fields from utility_structs.hh
These were causing clang compilation failures:

```sh
 [     CXX] src/cpu/pred/simple_btb.cc -> ALL/cpu/pred/simple_btb.o
In file included from src/cpu/testers/spatter_gen/spatter_gen.cc:29:
In file included from src/cpu/testers/spatter_gen/spatter_gen.hh:38:
src/cpu/testers/spatter_gen/utility_structs.hh:167:18: error: private field 'base' is not used [-Werror,-Wunused-private-field]
        uint32_t base;
                 ^
src/cpu/testers/spatter_gen/utility_structs.hh:211:14: error: private field 'index' is not used [-Werror,-Wunused-private-field]
    uint32_t index;
```

Change-Id: I927d277b6d1681593289f12447e735ad69ee44b8