stdlib: Return HTTP error for Azure Func API
Prior to this a very minimum error is returned which does not
print the error response. E.g:

```
AzureFunctionsAPIClientHttpJsonRequestError: Http Request to Azure Functions API failed.
Azure Functions API URL: https://api.gem5.org/api/resources
Data sent:

[
    {
        "id": "x86-ubuntu-22.4-boot",
        "resource_version": "None"
    }
]

Purpose of Request: Get Resources

```

This change ensures the HTTP response is printed, thus hopefully
telling the user what they did wrong. A typical example is a resource
ID being invalid.